# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_bullet_tmp_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bullet',
            name='tmp_follow',
        ),
        migrations.AddField(
            model_name='myuser',
            name='follows',
            field=models.ManyToManyField(related_name='_myuser_follows_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
