# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_auto_20170104_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='bullet',
            name='user_posted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
