# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0005_auto_20170105_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='user_images/None/no-avatar.jpg', upload_to='user_images/'),
        ),
    ]
